name: "Validate Gradle Wrapper"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Validate wrapper
        uses: gradle/actions/wrapper-validation@v6
